version: "3.9"

services:
  backend:
    build: .
    container_name: vastu_backend
    restart: always
    env_file:
      - .env
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
    ports:
      - "127.0.0.1:3030:3030"
    volumes:
      - whatsapp_session:/app/.wwebjs_auth

volumes:
  whatsapp_session:

networks:
  default:
    name: vastu_network
